import jsPDF from 'jspdf'

export interface InvoiceData {
  invoiceNumber: string
  productName: string
  buyerEmail: string
  sellerEmail: string
  amountUSD: number
  amountCrypto: number
  currency: string
  transactionHash: string
  walletAddress: string
  timestamp: Date
}

export function generateInvoicePDF(data: InvoiceData): string {
  const doc = new jsPDF()
  
  // Header
  doc.setFontSize(24)
  doc.setTextColor(16, 185, 129) // Green color
  doc.text('CryptoPayLink', 20, 30)
  
  doc.setFontSize(18)
  doc.setTextColor(0, 0, 0)
  doc.text('INVOICE', 20, 50)
  
  // Invoice details
  doc.setFontSize(12)
  doc.text(`Invoice #: ${data.invoiceNumber}`, 20, 70)
  doc.text(`Date: ${data.timestamp.toLocaleDateString()}`, 20, 85)
  
  // Product details
  doc.setFontSize(14)
  doc.text('Product Details', 20, 110)
  doc.setFontSize(12)
  doc.text(`Product: ${data.productName}`, 20, 130)
  doc.text(`Amount: $${data.amountUSD} USD`, 20, 145)
  doc.text(`Crypto Amount: ${data.amountCrypto} ${data.currency}`, 20, 160)
  
  // Payment details
  doc.setFontSize(14)
  doc.text('Payment Details', 20, 185)
  doc.setFontSize(12)
  doc.text(`Buyer: ${data.buyerEmail}`, 20, 205)
  doc.text(`Seller: ${data.sellerEmail}`, 20, 220)
  doc.text(`Wallet Address: ${data.walletAddress}`, 20, 235)
  doc.text(`Transaction Hash: ${data.transactionHash.substring(0, 40)}...`, 20, 250)
  
  // Footer
  doc.setFontSize(10)
  doc.setTextColor(128, 128, 128)
  doc.text('Generated by CryptoPayLink - Crypto Payment Platform', 20, 280)
  
  return doc.output('datauristring')
}
